### ISSUE TITLE
Spelling is the big sux

### ISSUE THREAD

**Issue by Shaptic** [pineapplegiant/color-palette#2]
Please fix: 
 - repo title,
 - the `<title>`, and
 - the `<h1>`

[**p a l e t t e**](https://www.thefreedictionary.com/palette)

God Bless,
--Some Guy

**Comment by pineapplegiant** [comment]
I am a big dumbo. Latest merge should fix the issue in all the variables, h1, readme and pic, even the repo name. Closing out.

Thx bro.
B l e ss🙏
